esphome:
  name: capteur-temp-esp
  friendly_name: "ESP32"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

# API Home Assistant
api:

# OTA correctement configur√©
ota:
  platform: esphome
  password: "xx34!!dddDD@"

wifi:
  ssid: "ssidname"
  password: "wifipass"

  manual_ip:
    static_ip: XXX.XXX.XXX.XXX
    gateway: XXX.XXX.XXX.XXX
    subnet: 255.255.255.0

  ap:
    ssid: "Esp32 Fallback Hotspot"
    password: "Password"
